---
title: "Multnomah County Schools Kindergarten Readiness"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(here)
library(ggiraph)
library(tmap)
library(sf)
library(leaflet)



multco_schools <- read_csv(here::here("data-clean", "multco-schools.csv")) %>% 
     st_as_sf(coords = c("lon", "lat"),
              crs = 4326)

multco_shapefile <- st_read(here::here("data-clean", "multco-shapefile.shp"))
poverty_shapefile <- st_read(here::here("data-clean", "poverty-shapefile.shp"))
```

Column {data-width=650}
-----------------------------------------------------------------------



### Chart C

```{r}

tmap_mode("view")

# tm_shape(poverty_shapefile) +
#      tm_polygons(col = "moe_pct",
#                  palette = "Blues",
#                  alpha = 0.5) +
tm_shape(multco_schools) +
     tm_dots(n = 5,
             size = .05,
             palette = "YlOrRd",
             col = "literacy_letter_sound") +
     tm_layout(title = "Test")

# tmaptools::palette_explorer() 

```

