---
title: "Multnomah County Schools Kindergarten Readiness"
author: "David Keyes"
output: radix::radix_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)

library(tidyverse)
library(here)
library(ggiraph)
library(tmap)
library(sf)
library(leaflet)
library(scales)
library(tinter)

# Colors

dk_blue <- "#004c97"
dk_orange <- "#DD8233"



multco_schools <- read_csv(here::here("data-clean", "multco-schools.csv")) %>% 
     st_as_sf(coords = c("lon", "lat"),
              crs = 4326)

multco_shapefile <- st_read(here::here("data-clean", "multco-shapefile.shp"))
poverty_shapefile <- st_read(here::here("data-clean", "poverty-shapefile.shp"))

tmap_mode("view")

```

```{r include = F}

approaches_mean <- multco_schools %>% 
     summarize(score = mean(approaches_total)) %>% 
     pull(score) %>% 
     round(1)

approaches <- multco_schools %>% 
     select(school,
            district,
            approaches_total) %>% 
     mutate(quartile = ntile(approaches_total, 4)) %>% 
     set_names(c("School", "District", "Score", "Quartile", "geometry")) %>% 
     mutate(label = str_glue("Score: {Score} (Average: {approaches_mean})"))

math_mean <- multco_schools %>% 
     summarize(score = mean(math_number)) %>% 
     pull(score) %>% 
     round(1)

math <- multco_schools %>% 
      select(school,
            district,
            math_number) %>% 
     mutate(quartile = ntile(math_number, 4)) %>% 
     set_names(c("School", "District", "Score", "Quartile", "geometry")) %>% 
     mutate(label = str_glue("Score: {Score} (Average: {math_mean})"))

literacy_mean <- multco_schools %>% 
     summarize(score = mean(literacy_letter_sound)) %>% 
     pull(score) %>% 
     round(1)

literacy <- multco_schools %>% 
      select(school,
            district,
            literacy_letter_sound) %>% 
     mutate(quartile = ntile(literacy_letter_sound, 4)) %>% 
     set_names(c("School", "District", "Score", "Quartile", "geometry")) %>% 
     mutate(label = str_glue("Score: {Score} (Average: {literacy_mean})"))

```


# Static






## Map

```{r include = F}

kreadiness_base_plot <- function () {
     ggplot() +
          # geom_sf(data = multco_shapefile) +
          geom_sf(data = poverty_shapefile,
                  color = "#eeeeee",
                  alpha = 0.5) +
          coord_sf(datum = NA) +
          theme_void() +
          # scale_color_viridis_c(option = "B",
          #                       direction = -1) +
          scale_color_gradientn(colours = tinter(dk_blue,
                                                 direction = "both")) +
          labs(color = "") +
          theme(legend.position = "bottom")
}
```


### Approaches

```{r layout="l-screen-inset", fig.height=5}

p <- kreadiness_base_plot() +
     geom_sf_interactive(data = filter(approaches, quartile != 1),
                         aes(tooltip = paste(school,
                                             "<br>",
                                             "Score: ",
                                             approaches_total,
                                             sep = "")),
             color = dk_blue,
             alpha = .2) +
     geom_sf_interactive(data = filter(approaches, quartile == 1),
                         aes(tooltip = paste(school,
                                             "<br>",
                                             "Score: ",
                                             approaches_total,
                                             sep = "")),
             color = dk_blue,
             size = 3,
             alpha = .95) +
     coord_sf(datum = NA) 

ggiraph(code = print(p))

```

### Math

```{r}



p <- kreadiness_base_plot() +
     geom_sf_interactive(data = filter(math, quartile != 1),
                         aes(tooltip = paste(school,
                                             "<br>",
                                             "Score: ",
                                             math_number,
                                             sep = "")),
             color = dk_blue,
             alpha = .2) +
     geom_sf_interactive(data = filter(math, quartile == 1),
                         aes(tooltip = paste(school,
                                             "<br>",
                                             "Score: ",
                                             math_number,
                                             sep = "")),
             color = dk_blue,
             size = 3,
             alpha = .95) +
     coord_sf(datum = NA) 

ggiraph(code = print(p))







```


### Literacy
```{r}


p <- kreadiness_base_plot() +
     geom_sf_interactive(data = filter(literacy, quartile != 1),
                         aes(tooltip = paste(school,
                                             "<br>",
                                             "Score: ",
                                             literacy_letter_sound,
                                             sep = "")),
             color = dk_blue,
             alpha = .2) +
     geom_sf_interactive(data = filter(literacy, quartile == 1),
                         aes(tooltip = paste(school,
                                             "<br>",
                                             "Score: ",
                                             literacy_letter_sound,
                                             sep = "")),
             color = dk_blue,
             size = 3,
             alpha = .95) +
     coord_sf(datum = NA) 

ggiraph(code = print(p))




```

## Map Interactive

### Approaches

```{r layout="l-screen-inset"}


tm_basemap(leaflet::providers$CartoDB.Positron) +
     tm_shape(filter(approaches, Quartile == 1)) +
     tm_dots(col = dk_blue,
             size = .1,
             alpha = 1,
             popup.vars = c("District", "label")) +
          tm_shape(filter(approaches, Quartile != 1)) +
     tm_dots(col = dk_blue,
             size = .05,
             popup.vars = c("District", "label"),
             alpha = 0.5)
```

### Literacy

```{r layout="l-screen-inset"}

tm_basemap(leaflet::providers$CartoDB.Positron) +
     tm_shape(filter(literacy, Quartile == 1)) +
     tm_dots(col = dk_blue,
             size = .1,
             alpha = 1,
             popup.vars = c("District", "label")) +
          tm_shape(filter(literacy, Quartile != 1)) +
     tm_dots(col = dk_blue,
             size = .05,
             popup.vars = c("District", "label"),
             alpha = 0.5)
```

### Math

```{r layout="l-screen-inset"}


tm_basemap(leaflet::providers$CartoDB.Positron) +
     tm_shape(filter(math, Quartile == 1)) +
     tm_dots(col = dk_blue,
             size = .1,
             alpha = 1,
             popup.vars = c("District", "label")) +
          tm_shape(filter(math, Quartile != 1)) +
     tm_dots(col = dk_blue,
             size = .05,
             popup.vars = c("District", "label"),
             alpha = 0.5)
```

## Scatterplot

### Approaches

```{r layout="l-screen-inset"}


p <- ggplot(multco_schools, aes(frl_pct, approaches_total)) +
     geom_smooth(method = "lm",
                 fill = "transparent",
                 color = dk_orange,
                 alpha = 0.5) +
     geom_point_interactive(aes(tooltip = paste("<strong>",school,"</strong>",
                                                "<br>",
                                                district, 
                                                "<br>",
                                                "Score: ",
                                                math_number,
                                                "<br>",
                                                "Percent Free and Reduced Lunch: ", 
                                                round(frl_pct, 0),
                                                sep = "")),
                            alpha = 0.75,
                            color = dk_blue) +
     
     scale_x_continuous(limits = c(0, 100)) +
     scale_y_continuous(limits = c(0, 5)) +
     theme_minimal() +
     labs(x = "Free and Reduced Lunch",
          y = "Score")

ggiraph(code = print(p))
```


### Math

```{r layout="l-screen-inset"}


p <- ggplot(multco_schools, aes(frl_pct, math_number)) +
     geom_smooth(method = "lm",
                 fill = "transparent",
                 color = dk_orange,
                 alpha = 0.5) +
     geom_point_interactive(aes(tooltip = paste("<strong>",school,"</strong>",
                                                "<br>",
                                                district, 
                                                "<br>",
                                                "Score: ",
                                                math_number,
                                                "<br>",
                                                "Percent Free and Reduced Lunch: ", 
                                                round(frl_pct, 0),
                                                sep = "")),
                            alpha = 0.75,
                            color = dk_blue) +
     
     scale_x_continuous(limits = c(0, 100)) +
     scale_y_continuous(limits = c(0, 15)) +
     theme_minimal() +
     labs(x = "Free and Reduced Lunch",
          y = "Score")

ggiraph(code = print(p))
```

### Literacy

```{r layout="l-screen-inset"}


p <- ggplot(multco_schools, aes(frl_pct, literacy_letter_sound)) +
     geom_smooth(method = "lm",
                 fill = "transparent",
                 color = dk_orange,
                 alpha = 0.5) +
     geom_point_interactive(aes(tooltip = paste("<strong>",school,"</strong>",
                                                "<br>",
                                                district, 
                                                "<br>",
                                                "Score: ",
                                                math_number,
                                                "<br>",
                                                "Percent Free and Reduced Lunch: ", 
                                                round(frl_pct, 0),
                                                sep = "")),
                            alpha = 0.75,
                            color = dk_blue) +
     
     scale_x_continuous(limits = c(0, 100)) +
     scale_y_continuous(limits = c(0, 20)) +
     theme_minimal() +
     labs(x = "Free and Reduced Lunch",
          y = "Score")

ggiraph(code = print(p))
```






